name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: test / default
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: brew install vim
      - uses: ./
      - run: vim --version
      - run: |
          vim -n -V1"$RUNNER_TEMP/vim.log" \
            +'call plug#begin()' \
            +'if v:errmsg != "" | cquit 1 | endif' \
            +'qall!'
      - run: cat "$RUNNER_TEMP/vim.log"

  test-autoload-dir:
    name: test / autoload-dir
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: brew install neovim
      - uses: ./
        with:
          autoload-dir: '$HOME/.local/share/nvim/site/autoload'
      - run: nvim --version
      - run: |
          nvim --headless -V1"$RUNNER_TEMP/nvim.log" \
            +'call plug#begin()' \
            +'if v:errmsg != "" | cquit 1 | endif' \
            +'qall!'
      - run: cat "$RUNNER_TEMP/nvim.log"
