name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: test / default
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: brew install vim
      - uses: ./
      - run: test -s "$HOME/.vim/autoload/plug.vim"
      - run: vim --version
      - run: |
          vim -es \
            +'call plug#begin()' \
            +'call writefile(v:errmsg ==# "" ? [] : [v:errmsg], $RUNNER_TEMP . "/log.txt")' \
            +'qall!'
      - run: cat "$RUNNER_TEMP/log.txt"
      - run: test ! -s "$RUNNER_TEMP/log.txt"

  test-autoload-dir:
    name: test / autoload-dir
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: brew install neovim
      - uses: ./
        with:
          autoload-dir: '$HOME/.local/share/nvim/site/autoload'
      - run: test -s "$HOME/.local/share/nvim/site/autoload/plug.vim"
      - run: nvim --version
      - run: |
          nvim --headless \
            +'call plug#begin()' \
            +'call writefile(v:errmsg ==# "" ? [] : [v:errmsg], $RUNNER_TEMP . "/log.txt")' \
            +'qall!'
      - run: cat "$RUNNER_TEMP/log.txt"
      - run: test ! -s "$RUNNER_TEMP/log.txt"
